### ISSUE TITLE
Using -t 300 causes error

### ISSUE THREAD

**Issue by KilianCroese** [mendix/cf-mendix-buildpack#122]
When i use cf push with the -t 300 parameter I get an error as described at:

https://docs.cloudfoundry.org/buildpacks/java/java-tips.html#slow-starting-java-or-grails-apps

> Note: The timeout threshold cannot exceed 180 seconds. Specifying a timeout threshold greater than 180 seconds results in the following error: 
[Server error, status code: 400, error code: 100001, message: The app is invalid: health_check_timeout maximum_exceeded](url)

Maybe the readme should be updated

**Comment by jtwaleson** [comment]
Hi @KilianCroese , good point, updated the docs.
