### ISSUE TITLE
HTTP redirect option

### ISSUE THREAD

**Issue by jtwaleson** [mendix/cf-mendix-buildpack#146]
With FORCE_HTTPS env var, we should enable the following nginx config:

        if ($http_x_forwarded_proto != "https") {
            return 301 https://$host$request_uri;
        }

**Comment by jtwaleson** [comment]
I started working on this in branch https, however, it does not work correctly on our own cloud v4 clusters due to a different http header being set. We use X-Forwarded-Scheme instead of the more standard X-Forwarded-Proto.

**Comment by cwesdorp** [comment]
Support for both headers is now supported by the runtime since [7.23.3](https://docs.mendix.com/releasenotes/studio-pro/7.23#fixes-1)
