### ISSUE TITLE
DDL execution timeout

### ISSUE THREAD

**Issue by jtwaleson** [mendix/cf-mendix-buildpack#148]
Sometimes DDL commands take longer than the startup timeout, which can lead to corrupt databases or endless startup loops (for databases with transaction support for DDL statements).

This can be fixed by changing the CF health check to `process` instead of `port` or `http`.

A better fix would be to start nginx in case DDL commands take too long, and then nginx will show 502 errors for as long as the app is still starting.

**Comment by cwesdorp** [comment]
will be handled with internal tickets.
