### ISSUE TITLE
Flaky test runs due to shared CF_HOME

### ISSUE THREAD

**Issue by xiwenc** [mendix/cf-mendix-buildpack#156]
Each test case should have its own dedicated `CF_HOME` to overcome possible concurrency issues in the cfcli:

- https://www.pivotaltracker.com/n/projects/892938/stories/128829195
- https://github.com/cloudfoundry/cli/issues/941

We should do this to improve the stability of test runs.

**Comment by joshp123** [comment]
A hacky workaround in the meantime: `git commit --allow-empty -m "Trigger CI"`, to trigger a new CI run.

**Comment by xiwenc** [comment]
There's a "restart build" in travis-ci. No need for that workaround
