### ISSUE TITLE
CF CLI version for test runs should be updated to the latest version.

### ISSUE THREAD

**Issue by joshp123** [mendix/cf-mendix-buildpack#157]
We're currently running [v6.3.0](https://github.com/cloudfoundry/cli/releases/tag/v6.30.0) from 1 Sep 2017.

We should potentially update this to a more recent version, to take advantage of recent bugfixes.

We could also opt to always use the latest version, but this is probably unwise - if they push a new version with a bug, then our builds will be broken.

**Comment by jtwaleson** [comment]
progtfo ;)

**Comment by djvdorp** [comment]
Don't use latest right now, but this one will work:
https://cli.run.pivotal.io/stable?release=debian64&version=6.35.1&source=github-rel
