### ISSUE TITLE
unify appd/new relic/datadog agents

### ISSUE THREAD

**Issue by jtwaleson** [mendix/cf-mendix-buildpack#173]
Currently the code the setup an AppDynamics agent, New Relic agent or DataDog agent is different.

They that datadog works (lib/datadog.py with very clear entry points) is the way to go. We should restructure the other options into the same way. That includes shipping the new relic agent with the buildpack, we should fetch it from a tar.gz on the CDN instead.

We should also add some tests to see if at least nothing breaks when appd/newrelic/datadog is activated.

**Comment by cwesdorp** [comment]
will done from internal tickets.
