### ISSUE TITLE
WARNING: specified heap size 256M is larger than max memory of the container (2048M), falling back to a heap size of 256M

### ISSUE THREAD

**Issue by djvdorp** [mendix/cf-mendix-buildpack#174]
I am not sure why we get this warning in the following case, it doesn't make much sense:
`WARNING: specified heap size 256M is larger than max memory of the container (2048M), falling back to a heap size of 256M`

Example from a CF app:
```
vcap@XXX:~$ echo $MEMORY_LIMIT
2048m
vcap@XXX:~$ echo $HEAP_SIZE 
256M
```

**Comment by joshp123** [comment]
@djvdorp - I don't think that this is the source of the problem, because we call `.upper()` on the string we pass to `re.search`.

I tested this in a container:
```python
>>> import os
>>> import re
>>> max_memory = os.environ.get('MEMORY_LIMIT')
>>> max_memory
'1024m'
>>> match = re.search('([0-9]+)M', max_memory.upper())
>>> match.group(1)
'1024'
```

**Comment by djvdorp** [comment]
@joshp123 ah, yeah, that's a very good catch. Not sure how I missed that. I still wonder why in the example of the container above I get the logline that says the same thing twice though then :confused:

**Comment by joshp123** [comment]
And, even if the regex didn't match, we would get an exception:
```

**Comment by joshp123** [comment]
Yes, the line itself is quite curious. Does this happen for all applications? Or only a subset? And do you have any idea how to reproduce?

**Comment by djvdorp** [comment]
Turns out that it is most likely a logic-error, there should be an `else` before this line in the code:
https://github.com/mendix/cf-mendix-buildpack/blob/83132760a4e17fb0503b867a763a9cf8fb5de50d/start.py#L267
