### ISSUE TITLE
Python3 version for test runs should be updated to the latest version. 

### ISSUE THREAD

**Issue by djvdorp** [mendix/cf-mendix-buildpack#176]
https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions

We can do 2 things here: either test with all Python3 versions we use (eg. 3.4 and upwards then) but maybe we should actually define multiple Python3 versions like 3.4, 3.5, 3.6 and maybe even 3.7 for future compatibility checks and potential regressions.

**Comment by joshp123** [comment]
Done in https://github.com/mendix/cf-mendix-buildpack/commit/49678b13a29f8d837abf617f0f150733152e7b83#diff-354f30a63fb0907d4ad57269548329e3

I think multiple Python versions is overkill for now, but could be useful later on. (Maybe we can enforce specific Python versions in code?)
