### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by spectejb** [mendix/cf-mendix-buildpack#200]
What is the license for cf-mendix-buildpack?  Any help would be greatly appreciated!

**Comment by AdamBrassard** [comment]
License is per app and per environment. This can be requested through Mendix Support. email: mxsupport@mendix.com.

I had to request a license that was for "on prem CF" which while not 100% accurate did give me the values I needed for ENV variables:

Name                    Value
LICENSE_ID         <UUID>
LICENSE_KEY      <Long base64 String>

**Comment by xiwenc** [comment]
@spectejb What do you mean with license for buildpack? Do you mind explaining what you are trying to do?

**Comment by spectejb** [comment]
Hey @xiwenc - I am looking for the open source license (e.g. MIT, BSD 3) so I understand what terms govern use.

**Comment by vasanramani** [comment]
I am having the same questions. What is the License model for using the buildpack in my own instance of CloudFoundry.  And why does the buildpack project not have a LICENSE.md file ?

**Comment by xiwenc** [comment]
Thank you for your interest! @vasanramani you are allowed to use it in your own CF. We are addressing the license internally now. Will get back to you.

**Comment by xiwenc** [comment]
@vasanramani @spectejb We have included the license (Apache License v2) with the buildpack as of version 2.2.4 (https://github.com/mendix/cf-mendix-buildpack/pull/211).
