### ISSUE TITLE
Make log subscriber optional

### ISSUE THREAD

**Issue by dudk** [mendix/cf-mendix-buildpack#256]
Hello,

We want to run Mendix app in CloudFoundry environment that uses custom logging service. In order to utilize it, we implemented a custom LogSubscriber. This part works as charm, but we came across FileSubscriber defined [here](https://github.com/mendix/cf-mendix-buildpack/blob/0a3ae37e4bbb4cc1ad2673134c6cd57ecc11166b/m2ee.yaml#L37). 

Because of it our logs are duplicated. We've found a way to silence it out, but it seems like a workaround and not a proper solution. Could you add this to your roadmap?

Thanks!

**Comment by cwesdorp** [comment]
@dudk can you please file in internal ticket for this with the relevant information? That allows PM to prioritise. Thanks!
