### ISSUE TITLE
CF Buildpack Should Support Oracle 

### ISSUE THREAD

**Issue by vjb** [mendix/cf-mendix-buildpack#266]
This buildpack should support Oracle.  Oracle is a Mendix supported database.  

Main changes need to be made in lib/database_config.py .  

Importantly, this would allow Docker deployments to leverage Oracle DB (since the docker buildpack builds upon this buildpack).

**Comment by cwesdorp** [comment]
@jobvs do you use VCAPs to bind the databases or JDBC connection strings; in any case, if you can provide an example that would be helpful.

**Comment by vjb** [comment]
We would be passing it through the docker buildpack flag DATABASE_URL, which would be jdbc

**Comment by cwesdorp** [comment]
@vjb I had a talk with @jaspervanderhoek. He is performing some investigation. Follow up will be in the internal ticketing system. I will close this item.

**Comment by xiwenc** [comment]
What is the outcome of this investigation? We also need this resolved. It would be helpful if you can share an example or instructions :) Thanks!
