### ISSUE TITLE
Cannot select an location of the Logging file

### ISSUE THREAD

**Issue by nmkleiberg** [mendix/cf-mendix-buildpack#268]
For a customer I use the docker buildpack (https://github.com/mendix/docker-mendix-buildpack/) for a deployment in Azure on Kubernetes.

At this moment I am searching for a solution regarding the logging files. On default, all the log files will be saved on the container itself. I want to specify a location where the application needs to store his log files.

Is it possible to make the Logging File location seperate of the BUILD_PATH.

For example,
If variable "LOGGING_LOCATION" is not specified the logging will be stored in the BUILD_PATH folder. When specified on the desired location.

**Comment by markbastiaans** [comment]
This issue has been open for quite some time - our apologies.

Your question relates to the Docker Mendix buildpack - I suggest you open an issue on that repository, as this project does not support scenarios outside of Cloud Foundry.
