### ISSUE TITLE
Plaintext debugger password in logging

### ISSUE THREAD

**Issue by ronaldburgman** [mendix/cf-mendix-buildpack#269]
https://github.com/mendix/cf-mendix-buildpack/blob/82d2e135e5e65d02f4eeb0fe954644e7f378edd0/start.py#L1141

Our security department is complaining that the debugger password is logged in plain-text if the debugger is enabled. Can the log level be changed from 'info' to 'debug', as is the case with the db connection string?

**Comment by cwesdorp** [comment]
Fixed with #277
