### ISSUE TITLE
how to use open jdk when deploying Mendix 8 on CF?

### ISSUE THREAD

**Issue by goldbergjeffrey** [mendix/cf-mendix-buildpack#272]
Current documentation references using Java 8 for setting up container via CLI. For deploying Mendix 8 to Cloud Foundry, is there a way through CLI to deploy with Open JDK?

**Comment by cwesdorp** [comment]
The build pack will determine the runtime version in use and download the selected java version based on that. For Mendix 8 this will be AdoptOpenJDK 11. We will update the documentation on this, it is outdated.

**Comment by cwesdorp** [comment]
@goldbergjeffrey could you please check our documentation update in PR #274 and let us know if you have feedback?

**Comment by cwesdorp** [comment]
Fixed with #277
