### ISSUE TITLE
Debugger not working when on a multi instance environment

### ISSUE THREAD

**Issue by woutervanmaasakker** [mendix/cf-mendix-buildpack#281]
Hi there,

We are trying to get Mendix running on CloudFoundry with multiple instances, so we have enough resources to handle all the traffic. It seems everything is working properly  except connecting with the debugger to the environment.

When trying to connect to https://[appurl]/debugger and tapping on the connect button, doesn’t do anything. When you check the logging you’ll see:

Debugging session started from [Source-IP: 127.0.0.1, X-Forwarded-For: xxx.xxx.xxx.xxx, User-Agent: Mendix Modeler 7.23.4].

It is required to connect to this multi instance invironment, because we see some strange activities when running in this mode....

I've posted this question also on the Mendix forum:
https://forum.mendixcloud.com/link/questions/96317

**Comment by cwesdorp** [comment]
Hello @woutervanmaasakker, currently we don't support multi-instance debugging. I will follow up on the forum and close this ticket.
