### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git'

### ISSUE THREAD

**Issue by nezoic** [mendix/cf-mendix-buildpack#286]
I'm attempting to build this in Azure Devops on an Ubuntu 18.04 host. I keep seeing this error but I'm not sure what it means other than 'git' is missing? Does this mean that git needs to be installed or this folder created?

`
Executing step 'Synchronize with file system'
 * Synchronizing with file system...
Executing step 'Initialize'
 * Preparing deployment...
Executing step 'Check prerequisites'
 * Checking for errors...
Executing step 'Clean deployment directory'
 * Cleaning deployment directory...
 * Cleaning web deployment directory...
Executing step 'Prepare deployment'
 * Writing files...
Executing step 'Build deployment structure'
 * Compiling Java...
 * Generating integration files...
 * Exporting a theme...
 * Exporting pages...
 * Optimizing...
 * Exporting custom widgets...
 * Bundling custom widgets...
 * Compiling JavaScript actions...
 * Compressing web resources...
Executing step 'Save model to deployment directory'
 * Saving model to deployment directory...
Executing step 'Create deployment package'
 * Creating deployment package...
Executing step 'Finalize deployment package'
BUILD SUCCEEDED
WARNING: MENDIX BUILDPACK: Unable to determine exact version in use. This is nothing to worry about
Traceback (most recent call last):
  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 65, in get_current_git_commit
    ["git", "rev-parse", "HEAD"], cwd=BUILDPACK_DIR
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
INFO: buildpack compile completed
`

**Comment by MXClyde** [comment]
As it says in the "WARNING" line, that warning can safely be ignored. It has no influence whatsoever on the resulting image/droplet. It has something to do with version control of the build pack itself, but I'll let the team maintaining the buildpack explain that themselves in more detail.

**Comment by nezoic** [comment]
@MXClyde I thought that might have been a warning for something else. I'm trying to figure out why m2ee is missing. This is a log from the pods that are stuck crashing.

INFO: Setting CF_INSTANCE_INDEX to 0 based on hostname mendix-k8s-stateful-0
INFO: Started Mendix Cloud Foundry Buildpack v1.7.3
sed: -e expression #1, char 94: unterminated `s' command
Traceback (most recent call last):
  File "/build/start.py", line 975, in <module>
    pre_process_m2ee_yaml()
  File "/build/start.py", line 60, in pre_process_m2ee_yaml
    '.local/m2ee.yaml'
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sed', '-i', 's|BUILD_PATH|/build|g; s|RUNTIME_PORT|81|; s|ADMIN_PORT|82|; s|ADMIN_PASSWORD|xxxxxxxxxx\r\n|', '.local/m2ee.yaml']' returned non-zero exit status 1
INFO: stopping app...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/build/start.py", line 811, in terminate_process
    if not m2ee.stop():
NameError: global name 'm2ee' is not defined
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/build/start.py", line 811, in terminate_process
    if not m2ee.stop():
NameError: global name 'm2ee' is not defined

**Comment by MXClyde** [comment]
I usually only see these types of errors when something went wrong during the build phase. So usually there is some clue in there. Which version of Mendix is used to create the model? Beware that you cannot build models created with versions that were recently retracted (e.g. 8.2.1) anymore...

**Comment by cwesdorp** [comment]
@nezoic Are you using the docker build pack? If so, which version? The docker build pack wraps the Mendix build pack master, but the version at the time of this report is 3.8 and your logs say "Cloud Foundry Buildpack v1.7.3". 

The git operations are used in the CloudFoundry base image to optimize retrieval of the Mendix runtime. In case you use another base image (e.g. with Docker) these warnings can safely be ignored. I'll advise retrying with the latest versions. If you run into issues please provide all logs, Mendix version and build packs versions you used. Thanks!.

**Comment by cwesdorp** [comment]
Closing based on inactivity.
