### ISSUE TITLE
SameSite workaround change is breaking custom cookies

### ISSUE THREAD

**Issue by icyitscold** [mendix/cf-mendix-buildpack#314]
https://github.com/mendix/cf-mendix-buildpack/commit/3af6b067254f4ad9601222b260dc56339c89fb7b

We have custom cookies added in a custom request handler that do not support HttpOnly which you are now adding. This unwanted infrastructure change has been added to our test and staging environments without warning. And, I'm guessing we will have a production issue upon the next reboot.

**Comment by carbone-kid** [comment]
@icyitscold could you please give more details regarding this issue? How HttpOnly is affecting functionality? We will revert these changes for now.

**Comment by icyitscold** [comment]
Sure.. We have a CustomRequestHandler for our Login page which will add a our own JWT cookie to the response. We have a custom front-end codebase that interacts with mendix via custom APIs and uses the JWT token for access. The vue codebase needs to read the cookie to present different user experiences based on the security profile, and to send token along as an authentication header for api requests.

**Comment by markbastiaans** [comment]
Thanks for your feedback and the explanation of your use case.

We have reverted the SameSite workaround pending a fix without the HttpOnly attribute. This issue can be closed.
