### ISSUE TITLE
Offline Section shows jre/jdk 8, when it should show 11 (for Mendix 8+)

### ISSUE THREAD

**Issue by vbeltrani** [mendix/cf-mendix-buildpack#338]
Offline Section shows jre/jdk 8, when it should show 11 (for Mendix 8+)

**Comment by markbastiaans** [comment]
Thanks for letting us know and apologies for the delay in responding.

We'll pick this documentation change up in a future change - I'll close this issue when that's done.

**Comment by markbastiaans** [comment]
Fixed in `develop`, will be part of upcoming release.
