### ISSUE TITLE
inline postgres certificates unsupported

### ISSUE THREAD

**Issue by basi01** [mendix/cf-mendix-buildpack#452]
I deploy a web app to a local cloudfoundry environment. As a database service for my DEV environment I have chosen a Marketplace service google-cloudsql-postgres with the plan postgres-db-f1-micro. Using the Web UI I created an instance with the name myapp-test-database and mentioned it in the CF Manifest:

    applications:
    - name: myapp-test
      services:
       - myapp-test-database

With this configuration the Mendix Runtime fails with:

    ERROR - ConnectionBus: Opening JDBC connection to Some(34.91.242.101) failed with SQLState: 08006 Error code: 0 Message: Could not open SSL certificate file -----BEGIN CERTIFICATE-----
    ...
    Caused by: java.io.FileNotFoundException: -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE----- (File name too long)

It's because the JDBC driver does not support inline certificates in `DATABASE_URL=postgres://user:pass@host?sslcert=-----BEGIN+CERTIFICATE-inlineCertificate... `

Here: https://github.com/mendix/cf-mendix-buildpack/blob/ce60432790e501e4237cbeca62b1a33c4849a77c/buildpack/runtime_components/database.py#L347
the jdbc params need to be parsed further, the inline certificates extracted to disk and PKCS#1 PEM key converted to PKCS#8 binary key that Postgres driver understands.

**Comment by markbastiaans** [comment]
Hi @basi01, thanks for reporting this.

Unfortunately this is not something we are planning on supporting, but we'd be happy to accept and review a PR with your proposed changes.

**Comment by markbastiaans** [comment]
Thanks for your contribution, @basi01!
Your PR which addresses this issue will be in the next buildpack release. Closing this issue.
