### ISSUE TITLE
Update AWS certs during build

### ISSUE THREAD

**Issue by zack817** [mendix/cf-mendix-buildpack#511]
The certs included in `etc/amazon-rds-ca.pem` dont seem to be enough (at least for GovCloud) wondering if they should be pulled during buildpack processing from the web:

- https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
- https://truststore.pki.us-gov-west-1.rds.amazonaws.com/global/global-bundle.pem

**Comment by Infra-Red** [comment]
Hi @zack817, thanks for reporting this issue!

That is correct, GovCloud certificates are not included in the `etc/amazon-rds-ca.pem`. Currently, only the following certs are included:
- [rds-ca-2019](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem)
- [Amazon root CA 1](https://www.amazontrust.com/repository/AmazonRootCA1.pem)

It would make sense to be able to expand `etc/amazon-rds-ca.pem` content and be able to add missing certificates (e.g. from an environment variable).  Unfortunately, GovCloud is not something we are planning on supporting, but we'd be happy to accept and review a PR.

**Comment by markbastiaans** [comment]
Since this is not something we can action now, I'm closing this issue. As mentioned, we welcome PRs!
