### ISSUE TITLE
Adopt OpenJDK - version uplift

### ISSUE THREAD

**Issue by JWHolding** [mendix/cf-mendix-buildpack#526]
The version of AdoptOpenJDK we are defaulting to (11.0.10) is quite out of date having been released over a year ago.

I realise that we can override this by providing the JAVA_VERSION env var but can the default version also be increased?

Happy to raise a PR but I'm not confident on what testing would need to be done to validate this

**Comment by markbastiaans** [comment]
Thanks for reporting, @JWHolding! We're picking this up as part of #527 - the hotfix has a new Adoptium minor version on board.
