### ISSUE TITLE
#516 Breaks buildpack when parameters < 5

### ISSUE THREAD

**Issue by JWHolding** [mendix/cf-mendix-buildpack#531]
#516 buildpack/stage.py line 30 declares deps_dir only when parameters >=5 
line 169 calls function `set_up_launch_environment()` (line 101) whether this variable is set or not. The functions then assumes that the variable would be declared (line 104) 
`util.set_up_launch_environment(DEPS_DIR, PROFILE_DIR)`

at this point buildpack fails with `NameError: name 'DEPS_DIR' is not defined`

i'm sorry but I don't yet have the experience with the buildpack to know whether conditionally calling `set_up_launch_environment` would be a valid solution. For context I am attempting to call the cf-mendix-buildpack from the docker-mendix-buildpack

**Comment by markbastiaans** [comment]
Hi @JWHolding - thanks for reporting this. As we can't support the Docker buildpack in this repository, please open an issue there.

**Comment by JWHolding** [comment]
Hi Its not an issue with the docker buildpack, just provided that for context, is the DEPS_DIR a required input? if not then the code in stage.py should deal with that
