### ISSUE TITLE
Build breaks - DEPS_DIR used before being assigned

### ISSUE THREAD

**Issue by Christophe-Vico** [mendix/cf-mendix-buildpack#532]
Tested with v.4.28.2 / v.4.28.4

Since we upgraded the Buildpack from 4.24.x to v4.28.x, our builds are failing with the error:

`INFO: Building from source completed
Traceback (most recent call last):
  File "/opt/mendix/buildpack/buildpack/stage.py", line 169, in <module>
    set_up_launch_environment()
  File "/opt/mendix/buildpack/buildpack/stage.py", line 104, in set_up_launch_environment
    util.set_up_launch_environment(DEPS_DIR, PROFILE_DIR)
NameError: name 'DEPS_DIR' is not defined
Traceback (most recent call last):
  File "./compilation", line 66, in <module>
    exit_code = call_buildpack_compilation()
  File "./compilation", line 38, in call_buildpack_compilation
    return subprocess.check_call(["/opt/mendix/buildpack/buildpack/stage.py", BUILD_PATH, CACHE_PATH])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/stage.py', '/opt/mendix/build', '/tmp/buildcache']' returned non-zero exit status 1.`  

In the code, we see that DEPS_DIR is assigned conditionally:

'if len(sys.argv) >= 5:
    DEPS_DIR = os.path.abspath(sys.argv[3])
    DEPS_IDX = os.path.abspath(sys.argv[4])
if len(sys.argv) >= 6 and sys.argv[5] != "":
    PROFILE_DIR = os.path.abspath(sys.argv[5])
else:
    PROFILE_DIR = os.path.abspath(os.path.join(BUILD_DIR, ".profile.d"))
'
but used in-conditionally:

'
def set_up_launch_environment():
    logging.debug("Creating buildpack launch environment...")
    util.mkdir_p(PROFILE_DIR)
    util.set_up_launch_environment(DEPS_DIR, PROFILE_DIR)
'

(util.set_up_launch_environment does not assign a default value to DEPS_DIR)

if DEPS_DIR assignment is conditional, we would expect it to have a default value, or some conditions before it's used
All the calls to stage.py we could track down were made with two arguments only BUILD_PATH & CACHE_PATH

**Comment by markbastiaans** [comment]
Hi @Christophe-Vico, thanks for reporting. Can you tell me what you mean with "our builds"?
This buildpack is meant to be used with Cloud Foundry, is that the case for you?

**Comment by Christophe-Vico** [comment]
Hi @markbastiaans, 
We use the docker-buildpack in parallel to Cloud Foundry for testing / developing.

What would be sensible default value to pass-on to stage.py for DEPS_DIR & DEPS_IDX to keep using our setup? (PROFILE_DIR is clear).

Thanks!

**Comment by markbastiaans** [comment]
Hi @Christophe-Vico - we don't support the Docker buildpack in this repository, as we can't test deployments on non-Cloud Foundry environments.

Please open an issue on https://github.com/mendix/docker-mendix-buildpack - the people maintaining this repository will get in touch with us if we need to change anything here.
