### ISSUE TITLE
cflinuxfs3 stack deprecated

### ISSUE THREAD

**Issue by ricketyrack** [mendix/cf-mendix-buildpack#615]
SAP BTP has deprecated cflinuxfs3 stack:  https://blogs.sap.com/2023/02/16/deprecation-of-cloud-foundry-stack-cflinuxfs3-and-migration-to-cflinuxfs4/
Support for cflinuxfs4 is needed.  Overriding the stack employed with the cf push -s cflinuxfs4 fails due to pinned dependencies not available in the new stack.

**Comment by ricketyrack** [comment]
I see there is already a pull request addressing this.  Sorry about that!

**Comment by ricketyrack** [comment]
Closing

**Comment by jpastoor** [comment]
Yes, feel free to try it out already and test it. Integration tests are failing on the MR but that has to do with the testing framework not playing along with newer versions.

**Comment by msvolenski** [comment]
Closing, since it was addressed with the release of cf-mendix-buildpack 5.0.0 (https://github.com/mendix/cf-mendix-buildpack/pull/639)
