### ISSUE TITLE
Piviotal Web Services DB String Info

### ISSUE THREAD

**Issue by jas5693a** [mendix/cf-mendix-buildpack#7]
Hello Everyone,

Can someone provide a valid example of  DATABASE_URL  value? 

How do you assign permissions? 

I have the runtime working on Piviotal Web Services but it can't make a database connection?

Thanks,

Jeff

**Comment by jtwaleson** [comment]
Hi Jeff,

On Pivotal Web Services the elephantsql plans will automatically set the DATABASE_URL value for you.

If you want to set it manually to connect to any postgres/mysql database, you should set up the environment variable like this:

DATABASE_TYPE://USERNAME:PASSWORD@DATABASE_HOST:PORT/DATABASE_NAME

Database type can be either "postgres" or "mysql" in the buildpack currently.
