### ISSUE TITLE
When pushing new app, mxadmin is no longer created.

### ISSUE THREAD

**Issue by tpoiesz** [mendix/cf-mendix-buildpack#70]
This bug was introduced when support for 'M2EE_PASSWORD' was added, it is caused by the following code in start.py:
In _create_admin_user_
```
if get_m2ee_password():
        logger.debug('M2EE_PASSWORD is set so skipping creation of application admin password')  
        return
```
```
def get_m2ee_password():
    m2ee_password = os.getenv('M2EE_PASSWORD', get_admin_password())
    if not m2ee_password:
        logger.warning('No M2EE_PASSWORD set, generating a random password for protection')
        m2ee_password = default_m2ee_password
    return m2ee_password
```

Since _get_m2ee_password_ always returns a non-Empty value(even if the env var is not set), the function _create_admin_user_ will never move past the if statement quoted above, meaning the admin user is not created.

**Comment by xiwenc** [comment]
@tpoiesz you're right we missed that case. `M2EE_PASSWORD` is introduced for better integration with automated systems like the Mendix Cloud Platform. Now the admin user is created/updated unless `M2EE_PASSWORD` is set.
