### ISSUE TITLE
Not able to push the application.

### ISSUE THREAD

**Issue by cfmagnum** [mendix/cf-mendix-buildpack#78]
Hi 
 
We are using  
 diego/1.4.1
 cf/250

In our cloud foundry marketplace there are following services
![screen shot 03-31-17 at 08 01 pm](https://cloud.githubusercontent.com/assets/13657881/24554943/f78ab0fe-164c-11e7-9695-0a5fd542e5c2.PNG)

We are using following stacks:- 
![screen shot 03-31-17 at 07 55 pm 001](https://cloud.githubusercontent.com/assets/13657881/24555024/368d8a10-164d-11e7-8cf7-349cc6b23f58.PNG)

After pushing the application 
https://github.com/mendix/MxPushNotifications and binding it with postgresql ,we got the following error.
![screen shot 03-31-17 at 07 55 pm](https://cloud.githubusercontent.com/assets/13657881/24555141/a664efb8-164d-11e7-9470-a65c48369046.PNG)

 Can you please help us with the issues?

Regards
Rahul

**Comment by xiwenc** [comment]
What are the exact commands that you have executed?

The repo you have linked is a custom widget, not a model that can be deployed as an app. There's an example/test app at https://github.com/mendix/MxPushNotifications/tree/master/test

so if you want to try that out:
```bash
git clone https://github.com/mendix/MxPushNotifications
cd test
# then follow https://github.com/mendix/cf-mendix-buildpack#push-your-app
```

**Comment by cfmagnum** [comment]
The steps that we are following are:-

1.git clone https://github.com/mendix/MxPushNotifications

2.cd MxPushNotifications/test

3.cf push MxPush -b https://github.com/mendix/cf-mendix-buildpack  --no-start

4.cf set-env MxPush CF_STARTUP_TIMEOUT 300

5.cf cs mysql default mysql

6.cf bs MxPush mysql

7.cf set-env MxPush LOGGING_CONFIG  '{ "<LOG NODE VALUE>": "DEBUG"}'

8. cf start MxPush 



Still we are getting the error:-
[output1.txt](https://github.com/mendix/cf-mendix-buildpack/files/889662/output1.txt)
 
and on starting app again error is:
[ouput2.txt](https://github.com/mendix/cf-mendix-buildpack/files/889667/ouput2.txt)

**Comment by jtwaleson** [comment]
That's odd. As a workaround you can create a Deployment Package from the modeler (you will get an .mda file), and then push that with `cf push -b ... -p path-to-deployment-package.mda`.

**Comment by cfmagnum** [comment]
Can you please suggest some pre-build .mda package as a example that we can push and try?

**Comment by cfmagnum** [comment]
The problem in we have services with name in "postgresql-db" in our cf marketplace.And when bind the app with "postgresql-db" it is giving error. 

WARNING: You should provide a DATABASE_URL by adding a database service to this application, it can be either MySQL or PostgresIf this is the first push of a new app, set up a database serviceand push again afterwards
Traceback (most recent call last):
  File "/tmp/buildpacks/1a5c1be73c6a68c3eecd0e7721e337fd/bin/compile", line 293, in <module>
    preflight_check()
  File "/tmp/buildpacks/1a5c1be73c6a68c3eecd0e7721e337fd/bin/compile", line 122, in preflight_check
    raise Exception('Missing environment variables')
Exception: Missing environment variables
Failed to compile droplet
Exit status 223

Its may be because in https://github.com/mendix/cf-mendix-buildpack/blob/master/lib/buildpackutil.py#L87, the name is **PostgreSQL**

We were facing same issue mysql too.  We have **mysql** in our marketplace and https://github.com/mendix/cf-mendix-buildpack/blob/master/lib/buildpackutil.py#L87 its **p-mysql**.

But for a try we change the name from **p-mysql** to **mysql** and it started throwing that error.

But for postgresSQL even after changing the name it is not working.

Can you please suggest something to work around,

**Comment by xiwenc** [comment]
As a workaround to use PostgreSQL you can set `DATABASE_URL`:
```
cf set-env myapp DATABASE_URL "postgres://user:pass@host:5432/dbname"
```

Make sure the postgresql service instance is bound to _myapp_ . You can get the jdbc url from `cf env myapp` and find it in the `VCAP_SERVICES` json dictionary. Restart the app.

To help support your database service can you supply examples of your `VCAP_SERVICES` dictionary with bound mysql and postgresql service instances? (Strip away hostnames and credentials).

**Comment by cfmagnum** [comment]
we followed the process you suggested and followed the steps :+1: 
1. cf push  MxPush -b https://github.com/mendix/cf-mendix-buildpack --no-start
2.cf set-env MxPush CF_STARTUP_TIMEOUT 300
3.cf set-env MxPush LOGGING_CONFIG  '{ "<LOG NODE VALUE>": "DEBUG"}'
4.cf bs MxPush postgresql-db
**5.cf env MxPush**
the file is 
[vcap-env.txt](https://github.com/mendix/cf-mendix-buildpack/files/892971/vcap-env.txt)
5.cf set-env MxPush DATABASE_URL postgresql://***.***.***.***:***.***.***.***@***.***.***.***:5435/da8a0092f_4b48_4955_8020_ab369ea4f76b

6.cf start MxPush.

And again we got the same error.

Starting app MxPush in org rahul / space rahul as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (16.3M)
Staging...
WARNING: You should provide a DATABASE_URL by adding a database service to this application, it can be either MySQL or PostgresIf this is the first push of a new app, set up a database serviceand push again afterwards
Traceback (most recent call last):
  File "/tmp/buildpacks/063299c9588a0e1d380502ed03d75f37/bin/compile", line 293, in <module>
    preflight_check()
  File "/tmp/buildpacks/063299c9588a0e1d380502ed03d75f37/bin/compile", line 122, in preflight_check
    raise Exception('Missing environment variables')
Exception: Missing environment variables
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

**Comment by xiwenc** [comment]
Thanks for the input so far!

I've improved the buildpack a bit. Can you test out my branch?

```
cf push MxPush -b https://github.com/mendix/cf-mendix-buildpack#gh_issue_78 --no-start
```

**Comment by cfmagnum** [comment]
Its working now!!
Thanks for the great support.

Can you please tell us the changes you performed? 

Thanks and regards 
Rahul Kumar

**Comment by xiwenc** [comment]
I think the core issue is that your URI value uses _postgresql_ while we expected _postgres_ as the protocol name. The change now also gives more details on why the database config detection failed. That missing informatie made it a bit hard to debug. Will try to get this merged into master asap. 

The full diff is: https://github.com/mendix/cf-mendix-buildpack/compare/gh_issue_78
